import { useReducer } from "react";
import Head from "next/head";
import { MainContext } from "../state";
import { initialState } from "../state";
import { mainReducer } from "@/state/reducers";
import { GET } from "@/utils/HTTP";
import CardList from "@/components/cardList";
import styles from "@/styles/Home.module.scss";
import MainLayout from "@/layouts/MainLayout";

export default function Home({ data }) {
  const [state, dispatch] = useReducer(mainReducer, initialState);

  return (
    <>
      <Head>
        <title>Next - Global State App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContext.Provider value={{ state, dispatch }}>
        <MainLayout>
          <main className={`${styles.Home}`}>
            <CardList data={data} />
          </main>
        </MainLayout>
      </MainContext.Provider>
    </>
  );
}

export async function getServerSideProps(context) {
  const data = await GET("people");

  return {
    props: {
      data,
    },
  };
}
